function pbs_run(array_size, array_id)
experiment_name = strcat('MCS_dataset', '01');

%output_dir=fullfile('./../OUT/', experiment_name);
output_dir=fullfile('/home/hxm_stu/WORK3/huangx/olr_out/', experiment_name);
%input_dir='~/MCS_AM/CAT/H5/';
input_dir='/home/hxm_stu/WORK3/huangx/olr/';
%source_code_path = '/home/hxm_stu/WORK1/hcq/MCS_v2/';
source_code_path = '/home/hxm_stu/WORK3/huangx/MCS_v1/';
%source_code_path = '~/Downloads/Track_new/MCS_tracking/code/';

addpath(genpath(source_code_path));

% Global tropical
% 198501 ~ 200812, 24*12 = 288
% 30N~30S
% Global tropical
% 195001 ~ 195112, 2*12 = 24
% 30N~30S
time_list = task_assign(1961, 11, 1961,11, array_size, array_id);  % 1 month
%time_list = task_assign(1950, 2, 1951,1, array_size, array_id); % 1*12=12 months

mcsDetect(input_dir, output_dir,...
    'is_rewrite', false,...
    'x1', 120, 'x2', 241,...
    'y1', 1, 'y2', 576,...
    'age_threshold', 3,...
    'tracking_method', 'TO',...
    'shield_temperature_threshold', 148,...
    'shield_area_threshold', 5000,...
    'overlapping_rate_threshold', 15,...
    'interest_date_begin', time_list.interest_begin_date,...
    'interest_date_end', time_list.interest_end_date,...
    'record_date_begin', time_list.record_begin_date,...
    'record_date_end', time_list.record_end_date)
