function [assignments,...
    unassignedTracks,...
    unassignedDetections,...
    to_decision_monitor]...
    = detectionToTrackAssignment(...
                tracking_method,...
                tracks,...
                list_component,...
                KF_distance_threshold,...
                overlapping_rate_threshold,...
                to_decision_monitor,...
                frame_index)
        
    if strcmpi(tracking_method,'trajectory')
        
        [assignments,...
         unassignedTracks,...
         unassignedDetections]=get_trajectory_assignment(...
                                    tracks,...
                                    list_component,...
                                    KF_distance_threshold);
                                
    elseif strcmpi(tracking_method,'overlapping')
        
        [assignments,...
         unassignedTracks,...
         unassignedDetections]=get_overlapping_assignment(...
                                    tracks,...
                                    list_component,...
                                    overlapping_rate_threshold);
                                
    elseif strcmpi(tracking_method,'TO')
        
        [assignments_t,...
         unassignedTracks_t,...
         unassignedDetections_t]=get_trajectory_assignment(...
                                    tracks,...
                                    list_component,...
                                    KF_distance_threshold);
                                
        [assignments_o,...
         unassignedTracks_o,...
         unassignedDetections_o]=get_overlapping_assignment(...
                                    tracks,...
                                    list_component,...
                                    overlapping_rate_threshold);
                                
        [assignments,...
         unassignedTracks,...
         unassignedDetections]=combine_overlapping_trajectory(...
                                    assignments_t,...
                                    assignments_o,...
                                    tracks,...
                                    list_component,...
                                    to_decision_monitor,...
                                    frame_index);
    end

end