function mcstracks = finalizeTracks()
% list variables used for record
    mcstracks = struct(...
        'id', {}, ... 
        'frames',{},... 
        'glat',{},...
        'glon',{},...
        'wlat',{},...
        'wlon',{},...
        'size',{},...
        'avg_temp',{},...
        'min_temp',{},...
        'list_time', {},...
        'list_speed', {},...
        'list_direct',{},...
        'list_grid',{},... 
        'list_deg',{},...
        'list_temp',{});        
end
