function tracks = initializeTracks()
    % list variables used for record
    % track id, count from begining of the time.
    % time stamp, count from begining of the time.
    tracks = struct(...
        'id', {}, ... 
        'kalmanFilter', {}, ...
        'x',{},...
        'y',{},...
        'list_core_x',{},...
        'list_core_y',{},...
        'list_shield_x',{},...
        'list_shield_y',{},...
        'list_shield',{},...
        'list_core',{},...
        'list_time',{},... 
        'list_pixel',{},...
        'list_temperature',{},...
        'list_low_temperature',{},...
        'list_avg_temperature',{},...
        'consective_invisible_count', {},...
        'is_mcs',{},...
        'age', {});
end

