function ncfile_name = monthIndex_2_filename(index)

    index = index - 1;
    interest_year = floor(index / 12);
    interest_month = mod(index, 12) + 1;
    ncfile_name = strcat('AM4.0_olr_', ...
        int2str(interest_year), ...
        '-', ...
        sprintf('%02d', interest_month), ...
        '.nc');
end

